# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: test-mc
  namespace: default # Namespace where the controller would watch
providerSpec:
  dummy-field: "provider-api based fields goes here"
secretRef: # If required
  name: test-secret
  namespace: default # Namespace where the controller would watch
provider: "Yandex"